# Generated by Django 2.2.5 on 2020-05-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nums', models.CharField(default='', help_text='客户端号', max_length=100, verbose_name='客户端号')),
                ('scroe', models.IntegerField(default='', help_text='分数', verbose_name='分数')),
            ],
        ),
    ]
