# Generated by Django 2.2.5 on 2020-05-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='scroe',
            new_name='score',
        ),
    ]
